grizzly-wave:
    topic_names: 
    - CustomTopicCreation
    - End
    - BeanProcessor
    prefix: wave
  # auto_create_topic: false
spring:
   kafka:
     bootstrap-servers: 192.168.99.100:9092
   
