grizzly-wave:
    topic_names: 
    - CustomTopicCreation
    - End
    - BeanProcessor
    prefix: wave
  # auto_create_topic: false
spring:
   kafka:
     bootstrap-servers: 192.168.99.100:9092
     consumer:
        group-id: "firstgroup"
        
logging:
  level:
    org:
      springframework:
        web: INFO
      apache.kafka: warn



