grizzly-wave:
    topic_names: 
    - CustomTopicCreation
    - End
    - BeanProcessor
    prefix: wave
  # auto_create_topic: false
spring:
   kafka:
     bootstrap-servers: 192.168.99.100:9092
      # used for kafka ssl connect...
#     sasl:
#       mechanism: PLAIN
#       jaas:
#         config: org.apache.kafka.common.security.plain.PlainLoginModule required username='IIB2526UB7AOB4HY' password='gTwgqPQeZNsIenMeuyoGmSi4yD4riLWGEQ9biO/pugvzPxuX2U8RIpwM2soyj1f6';
#       security:
#         status: enable
#         protocol: SASL_SSL
     consumer:
        group-id: "firstgroup"
        
logging:
  level:
    org:
      springframework:
        web: INFO
      apache.kafka: warn



